# This workflow validates the document for markup and examples.
name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Build and Validate Spec
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

   # Setup python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Setup Ruby environment  
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
         ruby-version: 2.7

    - name: Install Gemfile bundles
      run: bundle install --jobs 4 --retry 3

    - name: Build test manifests
      run: (cd tests; make)

    - name: Build implementation report
      run: (cd reports; bundle exec rake clean default)

    # Validate via ReSpec
    # See https://github.com/w3c/spec-prod/blob/main/docs/examples.md
    - name: ReSpec Checker
      uses: w3c/spec-prod@v2
      with:
        TOOLCHAIN: respec
        SOURCE: cg-spec/editors_draft.html
        VALIDATE_LINKS: false
        VALIDATE_MARKUP: true
    